@OperationsService_HostAddress = http://localhost:5103
@operatorId = 3fa85f64-5717-4562-b3fc-2c963f66afa6
@miningUnitId = 00000000-0000-0000-0000-000000000000
@fleetId = 00000000-0000-0000-0000-000000000000
@vehicleId = 00000000-0000-0000-0000-000000000000
@assignmentId = 00000000-0000-0000-0000-000000000000

POST {{OperationsService_HostAddress}}/api/v1/mining-units
Content-Type: application/json

{
  "businessCode": "um-antamina",
  "name": "Unidad Minera Antamina",
  "region": "Ancash"
}

###

GET {{OperationsService_HostAddress}}/api/v1/mining-units
Accept: application/json

###

PUT {{OperationsService_HostAddress}}/api/v1/mining-units/{{miningUnitId}}
Content-Type: application/json

{
  "name": "Unidad Minera Antamina - Tajo Norte",
  "region": "Ancash"
}

###

POST {{OperationsService_HostAddress}}/api/v1/mining-units/{{miningUnitId}}/locations
Content-Type: application/json

{
  "name": "Tajo Norte",
  "kind": "Pit"
}

###

POST {{OperationsService_HostAddress}}/api/v1/fleets
Content-Type: application/json

{
  "miningUnitId": "{{miningUnitId}}",
  "name": "Acarreo 1"
}

###

GET {{OperationsService_HostAddress}}/api/v1/fleets?miningUnitId={{miningUnitId}}
Accept: application/json

###

POST {{OperationsService_HostAddress}}/api/v1/vehicles
Content-Type: application/json

{
  "code": "CAT-797F-12",
  "model": "Caterpillar 797F",
  "fleetId": "{{fleetId}}"
}

###

GET {{OperationsService_HostAddress}}/api/v1/vehicles?fleetId={{fleetId}}
Accept: application/json

###

PUT {{OperationsService_HostAddress}}/api/v1/vehicles/{{vehicleId}}
Content-Type: application/json

{
  "model": "Caterpillar 797F",
  "status": "InMaintenance",
  "fleetId": "{{fleetId}}"
}

###

POST {{OperationsService_HostAddress}}/api/v1/operator-assignments
Content-Type: application/json

{
  "operatorId": "{{operatorId}}",
  "vehicleId": "{{vehicleId}}",
  "shift": "Day",
  "validFrom": "2026-10-01",
  "validTo": null
}

###

GET {{OperationsService_HostAddress}}/api/v1/operator-assignments/active?operatorId={{operatorId}}
Accept: application/json

###

GET {{OperationsService_HostAddress}}/api/v1/operator-assignments?operatorId={{operatorId}}
Accept: application/json

###

POST {{OperationsService_HostAddress}}/api/v1/operator-assignments/{{assignmentId}}/vehicle-change
Content-Type: application/json

{
  "newVehicleId": "{{vehicleId}}",
  "changeDate": "2026-10-10"
}

###

POST {{OperationsService_HostAddress}}/api/v1/operator-assignments/{{assignmentId}}/end
Content-Type: application/json

{
  "endDate": "2026-10-31"
}

###

GET {{OperationsService_HostAddress}}/api/v1/operator-assignments/context?operatorId={{operatorId}}&vehicleCode=CAT-797F-12&date=2026-10-07
Accept: application/json

###
