@FleetMonitoringService_HostAddress = http://localhost:5255
@operatorId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

POST {{FleetMonitoringService_HostAddress}}/api/v1/fleet-operators
Content-Type: application/json

{
  "operatorId": "{{operatorId}}",
  "fullName": "Juan Perez",
  "vehicleCode": "CAT-797-01",
  "fleet": "Haulage",
  "shift": "Night",
  "location": "Pit North"
}

###

GET {{FleetMonitoringService_HostAddress}}/api/v1/fleet-operators?shift=night&fleet=Haulage&riskLevel=critical
Accept: application/json

###

GET {{FleetMonitoringService_HostAddress}}/api/v1/fleet-operators/{{operatorId}}
Accept: application/json

###

PUT {{FleetMonitoringService_HostAddress}}/api/v1/fleet-operators/{{operatorId}}/risk-level
Content-Type: application/json

{
  "riskLevel": "Critical"
}

###

PUT {{FleetMonitoringService_HostAddress}}/api/v1/fleet-operators/{{operatorId}}/vehicle
Content-Type: application/json

{
  "vehicleCode": "CAT-797-07",
  "location": "Pit South"
}

###
